version: '3'

services:
  hyperdeck-app:
    build: .
    ports:
      - "80:5000"
    networks:
      - hyperdeck-network
    restart: always
    environment:
      - TELNET_IP=10.1.12.201
      - TELNET_PORT=9993

networks:
  hyperdeck-network:
    driver: bridge
