version: '3'

services:
  hyperdeck-app:
    build: .
    ports:
      - "80:5000"
    networks:
      - hyperdeck-network
    restart: always
    environment:
      - TELNET_IP=172.19.0.2
      - TELNET_PORT=9993

  mock-hyperdeck:
    build:
      context: ./mock_hyperdeck
    networks:
      - hyperdeck-network
    restart: always
    expose:
      - "9993"

networks:
  hyperdeck-network:
    driver: bridge
